create extension if not exists btree_gist with schema extensions;

create type public.app_role as enum ('customer', 'vendor', 'admin');
create type public.vehicle_approval_status as enum ('pending', 'approved', 'rejected');
create type public.booking_status as enum (
  'pending', 'confirmed', 'active', 'completed', 'cancelled', 'rejected'
);
create type public.payment_status as enum ('pending', 'paid', 'failed', 'refunded');

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  username text not null check (char_length(username) between 2 and 80),
  phone_number text,
  address text,
  avatar_url text,
  role public.app_role not null default 'customer',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.locations (
  id bigint generated by default as identity primary key,
  district text not null,
  name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (district, name)
);

create table public.vehicles (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references public.profiles (id) on delete set null,
  registration_number text not null unique,
  company text not null,
  name text not null,
  model text not null,
  title text,
  description text,
  year_made integer check (year_made between 1950 and 2100),
  fuel_type text check (fuel_type in ('petrol', 'diesel', 'electric', 'hybrid')),
  seats smallint check (seats between 1 and 60),
  transmission text check (transmission in ('manual', 'automatic')),
  car_type text,
  price_per_day numeric(12, 2) not null check (price_per_day >= 0),
  base_package text,
  district text not null,
  location text not null,
  rating numeric(2, 1) check (rating between 0 and 5),
  insurance_expires_on date,
  registration_expires_on date,
  pollution_certificate_expires_on date,
  approval_status public.vehicle_approval_status not null default 'pending',
  rejection_reason text,
  is_admin_added boolean not null default false,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.vehicle_images (
  id bigint generated by default as identity primary key,
  vehicle_id uuid not null references public.vehicles (id) on delete cascade,
  storage_path text,
  public_url text,
  position smallint not null default 0,
  created_at timestamptz not null default now(),
  check (storage_path is not null or public_url is not null),
  unique (vehicle_id, position)
);

create table public.bookings (
  id uuid primary key default gen_random_uuid(),
  vehicle_id uuid not null references public.vehicles (id) on delete restrict,
  customer_id uuid references public.profiles (id) on delete set null,
  pickup_at timestamptz not null,
  dropoff_at timestamptz not null,
  pickup_district text not null,
  pickup_location text not null,
  dropoff_location text not null,
  contact_email text not null,
  contact_phone text not null,
  contact_address text not null,
  rental_days integer not null check (rental_days > 0),
  daily_price numeric(12, 2) not null check (daily_price >= 0),
  delivery_fee numeric(12, 2) not null default 0 check (delivery_fee >= 0),
  discount numeric(12, 2) not null default 0 check (discount >= 0),
  total_price numeric(12, 2) not null check (total_price >= 0),
  currency char(3) not null default 'TZS',
  status public.booking_status not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  cancelled_at timestamptz,
  check (dropoff_at > pickup_at),
  constraint bookings_no_overlapping_vehicle_reservations
    exclude using gist (
      vehicle_id with =,
      tstzrange(pickup_at, dropoff_at, '[)') with &&
    ) where (status in ('pending', 'confirmed', 'active'))
);

create table public.payments (
  id uuid primary key default gen_random_uuid(),
  booking_id uuid not null references public.bookings (id) on delete restrict,
  provider text not null,
  provider_reference text,
  amount numeric(12, 2) not null check (amount >= 0),
  currency char(3) not null default 'TZS',
  status public.payment_status not null default 'pending',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, provider_reference)
);

create table public.booking_status_history (
  id bigint generated by default as identity primary key,
  booking_id uuid not null references public.bookings (id) on delete cascade,
  from_status public.booking_status,
  to_status public.booking_status not null,
  changed_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now()
);

create index vehicles_public_catalog_idx
  on public.vehicles (approval_status, district, location, model)
  where deleted_at is null;
create index vehicles_owner_idx on public.vehicles (owner_id);
create index bookings_customer_idx on public.bookings (customer_id, created_at desc);
create index bookings_vehicle_idx on public.bookings (vehicle_id, pickup_at, dropoff_at);
create index payments_booking_idx on public.payments (booking_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();
create trigger vehicles_set_updated_at before update on public.vehicles
for each row execute function public.set_updated_at();
create trigger bookings_set_updated_at before update on public.bookings
for each row execute function public.set_updated_at();
create trigger payments_set_updated_at before update on public.payments
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  requested_role public.app_role;
begin
  requested_role := case
    when new.raw_user_meta_data ->> 'role' = 'vendor' then 'vendor'::public.app_role
    else 'customer'::public.app_role
  end;

  insert into public.profiles (id, username, avatar_url, role)
  values (
    new.id,
    coalesce(
      nullif(new.raw_user_meta_data ->> 'username', ''),
      nullif(new.raw_user_meta_data ->> 'full_name', ''),
      split_part(coalesce(new.email, 'new-user'), '@', 1)
    ),
    coalesce(new.raw_user_meta_data ->> 'avatar_url', new.raw_user_meta_data ->> 'picture'),
    requested_role
  );
  return new;
end;
$$;

create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.current_app_role()
returns public.app_role
language sql
stable
security definer
set search_path = ''
as $$
  select role from public.profiles where id = (select auth.uid());
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(public.current_app_role() = 'admin'::public.app_role, false);
$$;

create or replace function public.can_access_booked_vehicle(p_vehicle_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.bookings
    where vehicle_id = p_vehicle_id and customer_id = (select auth.uid())
  );
$$;

create or replace function public.protect_vehicle_review_fields()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if pg_trigger_depth() > 1 then
    return new;
  end if;
  if not public.is_admin() then
    new.is_admin_added := old.is_admin_added;
    new.approval_status := 'pending';
    new.rejection_reason := null;
  end if;
  return new;
end;
$$;

create trigger vehicles_protect_review_fields
before update on public.vehicles
for each row execute function public.protect_vehicle_review_fields();

create or replace function public.register_as_vendor()
returns public.profiles
language plpgsql
security definer
set search_path = ''
as $$
declare
  result public.profiles;
begin
  if (select auth.uid()) is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  update public.profiles set role = 'vendor'
  where id = (select auth.uid()) and role = 'customer'
  returning * into result;

  if result.id is null then
    select * into result from public.profiles where id = (select auth.uid());
  end if;
  return result;
end;
$$;

create or replace function public.search_available_vehicles(
  p_pickup_at timestamptz,
  p_dropoff_at timestamptz,
  p_district text default null,
  p_location text default null
)
returns setof public.vehicles
language sql
stable
security definer
set search_path = ''
as $$
  select vehicle.* from public.vehicles as vehicle
  where vehicle.deleted_at is null
    and vehicle.approval_status = 'approved'
    and p_dropoff_at > p_pickup_at
    and (p_district is null or vehicle.district = p_district)
    and (p_location is null or vehicle.location = p_location)
    and not exists (
      select 1 from public.bookings as booking
      where booking.vehicle_id = vehicle.id
        and booking.status in ('pending', 'confirmed', 'active')
        and tstzrange(booking.pickup_at, booking.dropoff_at, '[)')
          && tstzrange(p_pickup_at, p_dropoff_at, '[)')
    )
  order by vehicle.price_per_day, vehicle.created_at desc;
$$;

create or replace function public.create_booking(
  p_vehicle_id uuid,
  p_pickup_at timestamptz,
  p_dropoff_at timestamptz,
  p_pickup_district text,
  p_pickup_location text,
  p_dropoff_location text,
  p_contact_email text,
  p_contact_phone text,
  p_contact_address text,
  p_payment_method text,
  p_coupon_code text default null
)
returns public.bookings
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_vehicle public.vehicles;
  created_booking public.bookings;
  number_of_days integer;
  pickup_support_fee numeric(12, 2) := 10000;
  booking_discount numeric(12, 2) := 0;
begin
  if (select auth.uid()) is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;
  if public.current_app_role() <> 'customer' then
    raise exception 'Only customers can create bookings' using errcode = '42501';
  end if;
  if p_dropoff_at <= p_pickup_at then
    raise exception 'Drop-off must be later than pickup' using errcode = '22007';
  end if;

  select * into selected_vehicle from public.vehicles
  where id = p_vehicle_id and deleted_at is null and approval_status = 'approved'
  for update;

  if selected_vehicle.id is null then
    raise exception 'Vehicle is not available' using errcode = 'P0002';
  end if;

  number_of_days := greatest(
    1,
    ceil(extract(epoch from (p_dropoff_at - p_pickup_at)) / 86400.0)::integer
  );
  booking_discount := case when upper(coalesce(p_coupon_code, '')) = 'KARIBU10000' then 10000 else 0 end;

  insert into public.bookings (
    vehicle_id, customer_id, pickup_at, dropoff_at, pickup_district,
    pickup_location, dropoff_location, contact_email, contact_phone,
    contact_address, rental_days, daily_price, delivery_fee, discount, total_price
  ) values (
    selected_vehicle.id, (select auth.uid()), p_pickup_at, p_dropoff_at,
    p_pickup_district, p_pickup_location, p_dropoff_location, p_contact_email,
    p_contact_phone, p_contact_address, number_of_days,
    selected_vehicle.price_per_day, pickup_support_fee,
    booking_discount,
    greatest(0, selected_vehicle.price_per_day * number_of_days + pickup_support_fee - booking_discount)
  ) returning * into created_booking;

  insert into public.payments (booking_id, provider, amount)
  values (created_booking.id, p_payment_method, created_booking.total_price);

  insert into public.booking_status_history (booking_id, to_status, changed_by)
  values (created_booking.id, created_booking.status, (select auth.uid()));
  return created_booking;
exception
  when exclusion_violation then
    raise exception 'Vehicle is already booked for the selected dates' using errcode = '23P01';
end;
$$;

create or replace function public.set_booking_status(
  p_booking_id uuid,
  p_status public.booking_status
)
returns public.bookings
language plpgsql
security definer
set search_path = ''
as $$
declare
  existing_booking public.bookings;
  updated_booking public.bookings;
  caller_role public.app_role;
begin
  caller_role := public.current_app_role();
  select * into existing_booking from public.bookings where id = p_booking_id for update;
  if existing_booking.id is null then
    raise exception 'Booking not found' using errcode = 'P0002';
  end if;
  if caller_role <> 'admin' and not exists (
    select 1 from public.vehicles
    where id = existing_booking.vehicle_id and owner_id = (select auth.uid())
  ) then
    raise exception 'Not allowed to update this booking' using errcode = '42501';
  end if;

  update public.bookings
  set status = p_status,
      cancelled_at = case when p_status = 'cancelled' then now() else cancelled_at end
  where id = p_booking_id
  returning * into updated_booking;

  insert into public.booking_status_history (booking_id, from_status, to_status, changed_by)
  values (updated_booking.id, existing_booking.status, updated_booking.status, (select auth.uid()));
  return updated_booking;
end;
$$;

create or replace function public.cancel_own_booking(p_booking_id uuid)
returns public.bookings
language plpgsql
security definer
set search_path = ''
as $$
declare
  existing_booking public.bookings;
  updated_booking public.bookings;
begin
  select * into existing_booking from public.bookings
  where id = p_booking_id and customer_id = (select auth.uid()) for update;
  if existing_booking.id is null then
    raise exception 'Booking not found' using errcode = 'P0002';
  end if;
  if existing_booking.status not in ('pending', 'confirmed') then
    raise exception 'This booking can no longer be cancelled' using errcode = 'P0001';
  end if;

  update public.bookings set status = 'cancelled', cancelled_at = now()
  where id = p_booking_id returning * into updated_booking;
  insert into public.booking_status_history (booking_id, from_status, to_status, changed_by)
  values (updated_booking.id, existing_booking.status, 'cancelled', (select auth.uid()));
  return updated_booking;
end;
$$;

create or replace function public.review_vehicle(
  p_vehicle_id uuid,
  p_approval_status public.vehicle_approval_status,
  p_rejection_reason text default null
)
returns public.vehicles
language plpgsql
security definer
set search_path = ''
as $$
declare
  result public.vehicles;
begin
  if not public.is_admin() then
    raise exception 'Admin access required' using errcode = '42501';
  end if;
  if p_approval_status = 'pending' then
    raise exception 'Review must approve or reject a vehicle' using errcode = '22023';
  end if;

  update public.vehicles
  set approval_status = p_approval_status,
      rejection_reason = case when p_approval_status = 'rejected' then p_rejection_reason else null end
  where id = p_vehicle_id returning * into result;
  return result;
end;
$$;

alter table public.profiles enable row level security;
alter table public.locations enable row level security;
alter table public.vehicles enable row level security;
alter table public.vehicle_images enable row level security;
alter table public.bookings enable row level security;
alter table public.payments enable row level security;
alter table public.booking_status_history enable row level security;

revoke all on public.profiles, public.locations, public.vehicles, public.vehicle_images,
  public.bookings, public.payments, public.booking_status_history from anon, authenticated;
grant select on public.locations, public.vehicles, public.vehicle_images to anon, authenticated;
grant select on public.profiles, public.bookings, public.payments, public.booking_status_history to authenticated;
grant update (username, phone_number, address, avatar_url) on public.profiles to authenticated;
grant insert, update on public.vehicles to authenticated;
grant insert, update, delete on public.vehicle_images to authenticated;
grant usage, select on all sequences in schema public to authenticated;

revoke all on function public.current_app_role(), public.is_admin(),
  public.can_access_booked_vehicle(uuid), public.register_as_vendor(),
  public.search_available_vehicles(timestamptz, timestamptz, text, text),
  public.create_booking(uuid, timestamptz, timestamptz, text, text, text, text, text, text, text, text),
  public.set_booking_status(uuid, public.booking_status), public.cancel_own_booking(uuid),
  public.review_vehicle(uuid, public.vehicle_approval_status, text) from public;
grant execute on function public.search_available_vehicles(timestamptz, timestamptz, text, text) to anon, authenticated;
grant execute on function public.current_app_role(), public.is_admin(),
  public.can_access_booked_vehicle(uuid), public.register_as_vendor(),
  public.create_booking(uuid, timestamptz, timestamptz, text, text, text, text, text, text, text, text),
  public.set_booking_status(uuid, public.booking_status), public.cancel_own_booking(uuid),
  public.review_vehicle(uuid, public.vehicle_approval_status, text) to authenticated;

create policy "profiles_select_own_or_admin" on public.profiles for select to authenticated
using (id = (select auth.uid()) or public.is_admin());
create policy "profiles_update_own" on public.profiles for update to authenticated
using (id = (select auth.uid())) with check (id = (select auth.uid()));
create policy "locations_public_read" on public.locations for select to anon, authenticated
using (is_active);
create policy "vehicles_public_read" on public.vehicles for select to anon, authenticated
using (approval_status = 'approved' and deleted_at is null);
create policy "vehicles_owner_or_admin_read" on public.vehicles for select to authenticated
using (owner_id = (select auth.uid()) or public.is_admin());
create policy "vehicles_booking_customer_read" on public.vehicles for select to authenticated
using (public.can_access_booked_vehicle(id));
create policy "vehicles_vendor_insert" on public.vehicles for insert to authenticated
with check (
  owner_id = (select auth.uid()) and public.current_app_role() = 'vendor'
  and approval_status = 'pending' and not is_admin_added
);
create policy "vehicles_admin_insert" on public.vehicles for insert to authenticated
with check (public.is_admin());
create policy "vehicles_owner_update" on public.vehicles for update to authenticated
using (owner_id = (select auth.uid()) and public.current_app_role() = 'vendor')
with check (owner_id = (select auth.uid()) and public.current_app_role() = 'vendor');
create policy "vehicles_admin_update" on public.vehicles for update to authenticated
using (public.is_admin()) with check (public.is_admin());

create policy "vehicle_images_public_read" on public.vehicle_images for select to anon, authenticated
using (exists (
  select 1 from public.vehicles where vehicles.id = vehicle_images.vehicle_id
    and (
      (vehicles.approval_status = 'approved' and vehicles.deleted_at is null)
      or public.can_access_booked_vehicle(vehicles.id)
    )
));
create policy "vehicle_images_owner_or_admin_read" on public.vehicle_images for select to authenticated
using (exists (
  select 1 from public.vehicles where vehicles.id = vehicle_images.vehicle_id
    and (vehicles.owner_id = (select auth.uid()) or public.is_admin())
));
create policy "vehicle_images_owner_or_admin_insert" on public.vehicle_images for insert to authenticated
with check (exists (
  select 1 from public.vehicles where vehicles.id = vehicle_images.vehicle_id
    and (vehicles.owner_id = (select auth.uid()) or public.is_admin())
));
create policy "vehicle_images_owner_or_admin_update" on public.vehicle_images for update to authenticated
using (exists (
  select 1 from public.vehicles where vehicles.id = vehicle_images.vehicle_id
    and (vehicles.owner_id = (select auth.uid()) or public.is_admin())
));
create policy "vehicle_images_owner_or_admin_delete" on public.vehicle_images for delete to authenticated
using (exists (
  select 1 from public.vehicles where vehicles.id = vehicle_images.vehicle_id
    and (vehicles.owner_id = (select auth.uid()) or public.is_admin())
));

create policy "bookings_participant_read" on public.bookings for select to authenticated
using (
  customer_id = (select auth.uid()) or public.is_admin()
  or exists (
    select 1 from public.vehicles
    where vehicles.id = bookings.vehicle_id and vehicles.owner_id = (select auth.uid())
  )
);
create policy "payments_participant_read" on public.payments for select to authenticated
using (exists (
  select 1 from public.bookings join public.vehicles on vehicles.id = bookings.vehicle_id
  where bookings.id = payments.booking_id
    and (bookings.customer_id = (select auth.uid())
      or vehicles.owner_id = (select auth.uid()) or public.is_admin())
));
create policy "booking_history_participant_read" on public.booking_status_history for select to authenticated
using (exists (
  select 1 from public.bookings join public.vehicles on vehicles.id = bookings.vehicle_id
  where bookings.id = booking_status_history.booking_id
    and (bookings.customer_id = (select auth.uid())
      or vehicles.owner_id = (select auth.uid()) or public.is_admin())
));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'vehicle-images', 'vehicle-images', true, 10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/avif']
)
on conflict (id) do nothing;

create policy "vehicle_images_storage_public_read" on storage.objects for select to anon, authenticated
using (bucket_id = 'vehicle-images');
create policy "vehicle_images_storage_insert" on storage.objects for insert to authenticated
with check (
  bucket_id = 'vehicle-images'
  and (storage.foldername(name))[1] = (select auth.uid())::text
  and public.current_app_role() in ('vendor', 'admin')
);
create policy "vehicle_images_storage_update" on storage.objects for update to authenticated
using (bucket_id = 'vehicle-images' and (storage.foldername(name))[1] = (select auth.uid())::text)
with check (bucket_id = 'vehicle-images' and (storage.foldername(name))[1] = (select auth.uid())::text);
create policy "vehicle_images_storage_delete" on storage.objects for delete to authenticated
using (
  bucket_id = 'vehicle-images'
  and ((storage.foldername(name))[1] = (select auth.uid())::text or public.is_admin())
);

insert into public.locations (district, name) values
  ('Dar es Salaam', 'Julius Nyerere International Airport'),
  ('Dar es Salaam', 'Masaki'),
  ('Dar es Salaam', 'Mlimani City'),
  ('Dar es Salaam', 'Kariakoo'),
  ('Arusha', 'Arusha Airport'),
  ('Arusha', 'Clocktower'),
  ('Arusha', 'Njiro'),
  ('Zanzibar', 'Abeid Amani Karume Airport'),
  ('Zanzibar', 'Stone Town'),
  ('Mwanza', 'Mwanza Airport'),
  ('Mwanza', 'Rock City Mall'),
  ('Dodoma', 'Dodoma Airport'),
  ('Dodoma', 'Nyerere Square')
on conflict (district, name) do nothing;
