create table public.booking_add_ons (
  code text primary key,
  name text not null,
  description text,
  price_type text not null check (price_type in ('per_booking', 'per_day')),
  price_amount numeric(12, 2) not null check (price_amount >= 0),
  applies_to text not null default 'rental' check (applies_to in ('rental', 'ride', 'subscription')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.business_accounts (
  id uuid primary key default gen_random_uuid(),
  company_name text not null check (char_length(company_name) between 2 and 160),
  tax_id text,
  invoice_email text,
  billing_address text not null,
  discount_percent numeric(5, 2) not null default 10 check (discount_percent between 0 and 50),
  monthly_billing_enabled boolean not null default true,
  status text not null default 'pending' check (status in ('pending', 'approved', 'suspended')),
  created_by uuid not null references public.profiles (id) on delete cascade,
  approved_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.business_account_members (
  id bigint generated by default as identity primary key,
  business_account_id uuid not null references public.business_accounts (id) on delete cascade,
  profile_id uuid not null references public.profiles (id) on delete cascade,
  member_role text not null default 'traveler' check (member_role in ('owner', 'manager', 'traveler')),
  created_at timestamptz not null default now(),
  unique (business_account_id, profile_id)
);

create table public.loyalty_accounts (
  customer_id uuid primary key references public.profiles (id) on delete cascade,
  tier text not null default 'silver' check (tier in ('silver', 'gold', 'platinum', 'diamond')),
  rental_points integer not null default 0 check (rental_points >= 0),
  status_points integer not null default 0 check (status_points >= 0),
  lifetime_spend numeric(12, 2) not null default 0 check (lifetime_spend >= 0),
  tier_expires_on date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.loyalty_transactions (
  id bigint generated by default as identity primary key,
  customer_id uuid not null references public.profiles (id) on delete cascade,
  booking_id uuid references public.bookings (id) on delete set null,
  points integer not null,
  transaction_type text not null check (transaction_type in ('earned', 'redeemed', 'expired', 'adjusted')),
  description text,
  created_at timestamptz not null default now()
);

alter table public.bookings
  add column if not exists business_account_id uuid references public.business_accounts (id) on delete set null,
  add column if not exists rental_product text not null default 'short_term',
  add column if not exists protection_package text not null default 'standard',
  add column if not exists mileage_package_km integer,
  add column if not exists selected_addons jsonb not null default '[]'::jsonb,
  add column if not exists subtotal numeric(12, 2) not null default 0,
  add column if not exists add_ons_total numeric(12, 2) not null default 0,
  add column if not exists one_way_fee numeric(12, 2) not null default 0,
  add column if not exists long_term_discount numeric(12, 2) not null default 0,
  add column if not exists loyalty_discount numeric(12, 2) not null default 0,
  add column if not exists business_discount numeric(12, 2) not null default 0,
  add column if not exists deposit_amount numeric(12, 2) not null default 0,
  add column if not exists cancellation_fee numeric(12, 2) not null default 0;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'bookings_rental_product_check'
      and conrelid = 'public.bookings'::regclass
  ) then
    alter table public.bookings
      add constraint bookings_rental_product_check
      check (rental_product in ('short_term', 'long_term', 'subscription'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'bookings_protection_package_check'
      and conrelid = 'public.bookings'::regclass
  ) then
    alter table public.bookings
      add constraint bookings_protection_package_check
      check (protection_package in ('standard', 'plus', 'premium'));
  end if;
end $$;

update public.bookings
set subtotal = daily_price * rental_days
where subtotal = 0;

create table public.booking_line_items (
  id bigint generated by default as identity primary key,
  booking_id uuid not null references public.bookings (id) on delete cascade,
  item_type text not null check (item_type in ('rent', 'fee', 'addon', 'discount', 'deposit', 'cancellation')),
  code text not null,
  description text not null,
  amount numeric(12, 2) not null,
  created_at timestamptz not null default now()
);

create table public.booking_amendments (
  id bigint generated by default as identity primary key,
  booking_id uuid not null references public.bookings (id) on delete cascade,
  changed_by uuid references public.profiles (id) on delete set null,
  previous_values jsonb not null default '{}'::jsonb,
  new_values jsonb not null default '{}'::jsonb,
  price_delta numeric(12, 2) not null default 0,
  created_at timestamptz not null default now()
);

create table public.fleet_blocks (
  id uuid primary key default gen_random_uuid(),
  vehicle_id uuid not null references public.vehicles (id) on delete cascade,
  block_type text not null check (block_type in ('maintenance', 'cleaning', 'document_expiry', 'private_use', 'manual')),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  reason text,
  created_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at > starts_at)
);

alter table public.fleet_blocks
  add constraint fleet_blocks_no_overlapping_blocks
  exclude using gist (
    vehicle_id with =,
    tstzrange(starts_at, ends_at, '[)') with &&
  );

create table public.invoices (
  id uuid primary key default gen_random_uuid(),
  invoice_number text not null unique,
  booking_id uuid references public.bookings (id) on delete set null,
  business_account_id uuid references public.business_accounts (id) on delete set null,
  customer_id uuid references public.profiles (id) on delete set null,
  subtotal numeric(12, 2) not null default 0,
  tax_amount numeric(12, 2) not null default 0,
  total_amount numeric(12, 2) not null default 0,
  currency char(3) not null default 'TZS',
  status text not null default 'issued' check (status in ('draft', 'issued', 'paid', 'void')),
  issued_at timestamptz not null default now(),
  due_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.profiles (id) on delete cascade,
  business_account_id uuid references public.business_accounts (id) on delete set null,
  vehicle_id uuid references public.vehicles (id) on delete set null,
  preferred_model text,
  monthly_price numeric(12, 2) not null check (monthly_price >= 0),
  mileage_package_km integer not null default 1000 check (mileage_package_km > 0),
  protection_package text not null default 'standard' check (protection_package in ('standard', 'plus', 'premium')),
  status text not null default 'pending' check (status in ('pending', 'active', 'paused', 'cancelled')),
  starts_at timestamptz not null,
  next_billing_at timestamptz not null,
  paused_until timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.ride_bookings (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid references public.profiles (id) on delete set null,
  business_account_id uuid references public.business_accounts (id) on delete set null,
  service_type text not null check (service_type in ('airport_transfer', 'one_way', 'hourly_chauffeur')),
  pickup_at timestamptz not null,
  pickup_location text not null,
  destination_location text,
  hours integer check (hours is null or hours > 0),
  passenger_count smallint not null default 1 check (passenger_count between 1 and 12),
  luggage_count smallint not null default 0 check (luggage_count between 0 and 20),
  ride_class text not null default 'standard' check (ride_class in ('standard', 'business', 'first', 'green', 'xl')),
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'active', 'completed', 'cancelled')),
  estimated_price numeric(12, 2) not null default 0,
  currency char(3) not null default 'TZS',
  contact_email text not null,
  contact_phone text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists business_accounts_created_by_idx on public.business_accounts (created_by);
create index if not exists business_account_members_profile_idx on public.business_account_members (profile_id, business_account_id);
create index if not exists loyalty_transactions_customer_idx on public.loyalty_transactions (customer_id, created_at desc);
create index if not exists bookings_business_account_idx on public.bookings (business_account_id, created_at desc);
create index if not exists booking_line_items_booking_idx on public.booking_line_items (booking_id);
create index if not exists fleet_blocks_vehicle_range_idx on public.fleet_blocks using gist (vehicle_id, tstzrange(starts_at, ends_at, '[)'));
create index if not exists invoices_booking_idx on public.invoices (booking_id);
create index if not exists invoices_business_idx on public.invoices (business_account_id, issued_at desc);
create index if not exists subscriptions_customer_idx on public.subscriptions (customer_id, status);
create index if not exists subscriptions_business_idx on public.subscriptions (business_account_id, status);
create index if not exists ride_bookings_customer_idx on public.ride_bookings (customer_id, pickup_at desc);

create trigger booking_add_ons_set_updated_at before update on public.booking_add_ons
for each row execute function public.set_updated_at();
create trigger business_accounts_set_updated_at before update on public.business_accounts
for each row execute function public.set_updated_at();
create trigger loyalty_accounts_set_updated_at before update on public.loyalty_accounts
for each row execute function public.set_updated_at();
create trigger fleet_blocks_set_updated_at before update on public.fleet_blocks
for each row execute function public.set_updated_at();
create trigger subscriptions_set_updated_at before update on public.subscriptions
for each row execute function public.set_updated_at();
create trigger ride_bookings_set_updated_at before update on public.ride_bookings
for each row execute function public.set_updated_at();

insert into public.booking_add_ons (code, name, description, price_type, price_amount) values
  ('extra_driver', 'Extra driver', 'Add one approved additional driver to the rental.', 'per_day', 12000),
  ('child_seat', 'Child seat', 'Reserve a child safety seat for the trip.', 'per_booking', 20000),
  ('airport_meet', 'Airport meet and greet', 'A team member meets the renter at airport pickup.', 'per_booking', 30000),
  ('unlimited_mileage', 'Unlimited mileage', 'Remove daily mileage limits for local travel.', 'per_day', 18000),
  ('vehicle_delivery', 'Vehicle delivery', 'Deliver the vehicle to the selected pickup address.', 'per_booking', 25000)
on conflict (code) do update
set name = excluded.name,
    description = excluded.description,
    price_type = excluded.price_type,
    price_amount = excluded.price_amount,
    is_active = true;

create or replace function public.ensure_loyalty_account(p_customer_id uuid)
returns public.loyalty_accounts
language plpgsql
security definer
set search_path = ''
as $$
declare
  result public.loyalty_accounts;
begin
  if (select auth.uid()) is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;
  if p_customer_id <> (select auth.uid()) and not public.is_admin() then
    raise exception 'Not allowed to manage this loyalty account' using errcode = '42501';
  end if;

  insert into public.loyalty_accounts (customer_id)
  values (p_customer_id)
  on conflict (customer_id) do nothing;

  select * into result
  from public.loyalty_accounts
  where customer_id = p_customer_id;

  return result;
end;
$$;

create or replace function public.is_business_member(p_business_account_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.business_account_members member
    join public.business_accounts account on account.id = member.business_account_id
    where member.business_account_id = p_business_account_id
      and member.profile_id = (select auth.uid())
      and account.status = 'approved'
  );
$$;

create or replace function public.quote_booking(
  p_vehicle_id uuid,
  p_pickup_at timestamptz,
  p_dropoff_at timestamptz,
  p_pickup_district text,
  p_pickup_location text,
  p_dropoff_location text,
  p_coupon_code text default null,
  p_add_on_codes text[] default '{}'::text[],
  p_business_account_id uuid default null,
  p_mileage_package_km integer default null,
  p_protection_package text default 'standard'
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  selected_vehicle public.vehicles;
  loyalty public.loyalty_accounts;
  rental_days integer;
  rental_product text;
  rent_subtotal numeric(12, 2);
  delivery_fee numeric(12, 2) := 10000;
  one_way_fee numeric(12, 2) := 0;
  protection_fee numeric(12, 2) := 0;
  mileage_fee numeric(12, 2) := 0;
  add_on_total numeric(12, 2) := 0;
  gross_total numeric(12, 2);
  coupon_discount numeric(12, 2) := 0;
  long_discount numeric(12, 2) := 0;
  member_discount numeric(12, 2) := 0;
  corporate_discount numeric(12, 2) := 0;
  discount_total numeric(12, 2);
  final_total numeric(12, 2);
  deposit numeric(12, 2);
  line_items jsonb := '[]'::jsonb;
  current_user_id uuid := (select auth.uid());
begin
  if p_dropoff_at <= p_pickup_at then
    raise exception 'Drop-off must be later than pickup' using errcode = '22007';
  end if;
  if coalesce(p_protection_package, 'standard') not in ('standard', 'plus', 'premium') then
    raise exception 'Unsupported protection package' using errcode = '22023';
  end if;

  select * into selected_vehicle
  from public.vehicles
  where id = p_vehicle_id
    and deleted_at is null
    and approval_status = 'approved';

  if selected_vehicle.id is null then
    raise exception 'Vehicle is not available' using errcode = 'P0002';
  end if;

  if exists (
    select 1
    from public.bookings booking
    where booking.vehicle_id = selected_vehicle.id
      and booking.status in ('pending', 'confirmed', 'active')
      and tstzrange(booking.pickup_at, booking.dropoff_at, '[)')
        && tstzrange(p_pickup_at, p_dropoff_at, '[)')
  ) or exists (
    select 1
    from public.fleet_blocks block
    where block.vehicle_id = selected_vehicle.id
      and tstzrange(block.starts_at, block.ends_at, '[)')
        && tstzrange(p_pickup_at, p_dropoff_at, '[)')
  ) then
    raise exception 'Vehicle is already booked or blocked for the selected dates' using errcode = '23P01';
  end if;

  rental_days := greatest(1, ceil(extract(epoch from (p_dropoff_at - p_pickup_at)) / 86400.0)::integer);
  rental_product := case when rental_days >= 28 then 'long_term' else 'short_term' end;
  rent_subtotal := selected_vehicle.price_per_day * rental_days;
  one_way_fee := case when lower(coalesce(p_pickup_location, '')) <> lower(coalesce(p_dropoff_location, '')) then 25000 else 0 end;
  protection_fee := case coalesce(p_protection_package, 'standard')
    when 'plus' then rental_days * 15000
    when 'premium' then rental_days * 25000
    else 0
  end;
  mileage_fee := case
    when coalesce(p_mileage_package_km, 0) >= 2000 then 50000
    when coalesce(p_mileage_package_km, 0) >= 1000 then 25000
    else 0
  end;

  select coalesce(sum(
    case add_on.price_type
      when 'per_day' then add_on.price_amount * rental_days
      else add_on.price_amount
    end
  ), 0)
  into add_on_total
  from public.booking_add_ons add_on
  where add_on.code = any(coalesce(p_add_on_codes, '{}'::text[]))
    and add_on.applies_to = 'rental'
    and add_on.is_active;

  coupon_discount := case when upper(coalesce(p_coupon_code, '')) = 'KARIBU10000' then 10000 else 0 end;
  long_discount := case
    when rental_days >= 90 then rent_subtotal * 0.15
    when rental_days >= 28 then rent_subtotal * 0.10
    else 0
  end;

  if current_user_id is not null and p_business_account_id is null then
    select * into loyalty
    from public.loyalty_accounts
    where customer_id = current_user_id;

    member_discount := case loyalty.tier
      when 'diamond' then rent_subtotal * 0.10
      when 'platinum' then rent_subtotal * 0.08
      when 'gold' then rent_subtotal * 0.05
      else rent_subtotal * 0.02
    end;
  end if;

  if p_business_account_id is not null then
    if not public.is_business_member(p_business_account_id) then
      raise exception 'Not allowed to use this business account' using errcode = '42501';
    end if;

    select rent_subtotal * (account.discount_percent / 100.0)
    into corporate_discount
    from public.business_accounts account
    where account.id = p_business_account_id and account.status = 'approved';
  end if;

  gross_total := rent_subtotal + delivery_fee + one_way_fee + protection_fee + mileage_fee + add_on_total;
  discount_total := least(gross_total, coupon_discount + long_discount + member_discount + coalesce(corporate_discount, 0));
  final_total := greatest(0, gross_total - discount_total);
  deposit := greatest(50000, round(final_total * 0.15, 2));

  line_items := line_items || jsonb_build_array(jsonb_build_object('type', 'rent', 'code', 'daily_rent', 'description', 'Rental days', 'amount', rent_subtotal));
  line_items := line_items || jsonb_build_array(jsonb_build_object('type', 'fee', 'code', 'pickup_support', 'description', 'Pickup support', 'amount', delivery_fee));
  if one_way_fee > 0 then
    line_items := line_items || jsonb_build_array(jsonb_build_object('type', 'fee', 'code', 'one_way', 'description', 'Different return location', 'amount', one_way_fee));
  end if;
  if protection_fee > 0 then
    line_items := line_items || jsonb_build_array(jsonb_build_object('type', 'addon', 'code', 'protection', 'description', initcap(p_protection_package) || ' protection', 'amount', protection_fee));
  end if;
  if mileage_fee > 0 then
    line_items := line_items || jsonb_build_array(jsonb_build_object('type', 'addon', 'code', 'mileage_package', 'description', 'Mileage package', 'amount', mileage_fee));
  end if;
  if add_on_total > 0 then
    line_items := line_items || (
      select coalesce(jsonb_agg(jsonb_build_object(
        'type', 'addon',
        'code', add_on.code,
        'description', add_on.name,
        'amount', case add_on.price_type when 'per_day' then add_on.price_amount * rental_days else add_on.price_amount end
      )), '[]'::jsonb)
      from public.booking_add_ons add_on
      where add_on.code = any(coalesce(p_add_on_codes, '{}'::text[]))
        and add_on.applies_to = 'rental'
        and add_on.is_active
    );
  end if;
  if discount_total > 0 then
    line_items := line_items || jsonb_build_array(jsonb_build_object('type', 'discount', 'code', 'discounts', 'description', 'Applied discounts', 'amount', -discount_total));
  end if;
  line_items := line_items || jsonb_build_array(jsonb_build_object('type', 'deposit', 'code', 'security_deposit', 'description', 'Refundable security deposit estimate', 'amount', deposit));

  return jsonb_build_object(
    'vehicle_id', selected_vehicle.id,
    'rental_days', rental_days,
    'rental_product', rental_product,
    'daily_price', selected_vehicle.price_per_day,
    'subtotal', rent_subtotal,
    'delivery_fee', delivery_fee,
    'one_way_fee', one_way_fee,
    'protection_fee', protection_fee,
    'mileage_fee', mileage_fee,
    'add_ons_total', add_on_total,
    'coupon_discount', coupon_discount,
    'long_term_discount', long_discount,
    'loyalty_discount', member_discount,
    'business_discount', coalesce(corporate_discount, 0),
    'discount', discount_total,
    'total_price', final_total,
    'deposit_amount', deposit,
    'currency', 'TZS',
    'line_items', line_items
  );
end;
$$;

create or replace function public.search_available_vehicles(
  p_pickup_at timestamptz,
  p_dropoff_at timestamptz,
  p_district text default null,
  p_location text default null
)
returns setof public.vehicles
language sql
stable
security definer
set search_path = ''
as $$
  select vehicle.* from public.vehicles as vehicle
  where vehicle.deleted_at is null
    and vehicle.approval_status = 'approved'
    and p_dropoff_at > p_pickup_at
    and (p_district is null or vehicle.district = p_district)
    and (p_location is null or vehicle.location = p_location)
    and not exists (
      select 1 from public.bookings as booking
      where booking.vehicle_id = vehicle.id
        and booking.status in ('pending', 'confirmed', 'active')
        and tstzrange(booking.pickup_at, booking.dropoff_at, '[)')
          && tstzrange(p_pickup_at, p_dropoff_at, '[)')
    )
    and not exists (
      select 1 from public.fleet_blocks as block
      where block.vehicle_id = vehicle.id
        and tstzrange(block.starts_at, block.ends_at, '[)')
          && tstzrange(p_pickup_at, p_dropoff_at, '[)')
    )
  order by vehicle.price_per_day, vehicle.created_at desc;
$$;

drop function if exists public.create_booking(
  uuid, timestamptz, timestamptz, text, text, text, text, text, text, text, text
);

create or replace function public.create_booking(
  p_vehicle_id uuid,
  p_pickup_at timestamptz,
  p_dropoff_at timestamptz,
  p_pickup_district text,
  p_pickup_location text,
  p_dropoff_location text,
  p_contact_email text,
  p_contact_phone text,
  p_contact_address text,
  p_payment_method text,
  p_coupon_code text default null,
  p_add_on_codes text[] default '{}'::text[],
  p_business_account_id uuid default null,
  p_mileage_package_km integer default null,
  p_protection_package text default 'standard'
)
returns public.bookings
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_vehicle public.vehicles;
  created_booking public.bookings;
  price_quote jsonb;
  item jsonb;
begin
  if (select auth.uid()) is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;
  if public.current_app_role() <> 'customer' then
    raise exception 'Only customers can create bookings' using errcode = '42501';
  end if;

  select * into selected_vehicle
  from public.vehicles
  where id = p_vehicle_id
    and deleted_at is null
    and approval_status = 'approved'
  for update;

  if selected_vehicle.id is null then
    raise exception 'Vehicle is not available' using errcode = 'P0002';
  end if;

  price_quote := public.quote_booking(
    p_vehicle_id, p_pickup_at, p_dropoff_at, p_pickup_district, p_pickup_location,
    p_dropoff_location, p_coupon_code, p_add_on_codes, p_business_account_id,
    p_mileage_package_km, p_protection_package
  );

  insert into public.bookings (
    vehicle_id, customer_id, business_account_id, pickup_at, dropoff_at, pickup_district,
    pickup_location, dropoff_location, contact_email, contact_phone, contact_address,
    rental_days, daily_price, delivery_fee, discount, total_price, rental_product,
    protection_package, mileage_package_km, selected_addons, subtotal, add_ons_total,
    one_way_fee, long_term_discount, loyalty_discount, business_discount, deposit_amount
  ) values (
    selected_vehicle.id, (select auth.uid()), p_business_account_id, p_pickup_at, p_dropoff_at,
    p_pickup_district, p_pickup_location, p_dropoff_location, p_contact_email,
    p_contact_phone, p_contact_address, (price_quote ->> 'rental_days')::integer,
    (price_quote ->> 'daily_price')::numeric, (price_quote ->> 'delivery_fee')::numeric,
    (price_quote ->> 'discount')::numeric, (price_quote ->> 'total_price')::numeric,
    price_quote ->> 'rental_product', coalesce(p_protection_package, 'standard'),
    p_mileage_package_km, to_jsonb(coalesce(p_add_on_codes, '{}'::text[])),
    (price_quote ->> 'subtotal')::numeric,
    (price_quote ->> 'add_ons_total')::numeric
      + (price_quote ->> 'protection_fee')::numeric
      + (price_quote ->> 'mileage_fee')::numeric,
    (price_quote ->> 'one_way_fee')::numeric, (price_quote ->> 'long_term_discount')::numeric,
    (price_quote ->> 'loyalty_discount')::numeric, (price_quote ->> 'business_discount')::numeric,
    (price_quote ->> 'deposit_amount')::numeric
  ) returning * into created_booking;

  for item in select * from jsonb_array_elements(price_quote -> 'line_items')
  loop
    insert into public.booking_line_items (booking_id, item_type, code, description, amount)
    values (
      created_booking.id,
      item ->> 'type',
      item ->> 'code',
      item ->> 'description',
      (item ->> 'amount')::numeric
    );
  end loop;

  insert into public.payments (booking_id, provider, amount)
  values (created_booking.id, p_payment_method, created_booking.total_price);

  insert into public.booking_status_history (booking_id, to_status, changed_by)
  values (created_booking.id, created_booking.status, (select auth.uid()));
  return created_booking;
exception
  when exclusion_violation then
    raise exception 'Vehicle is already booked for the selected dates' using errcode = '23P01';
end;
$$;

create or replace function public.modify_own_booking(
  p_booking_id uuid,
  p_pickup_at timestamptz,
  p_dropoff_at timestamptz,
  p_dropoff_location text,
  p_coupon_code text default null,
  p_add_on_codes text[] default '{}'::text[],
  p_mileage_package_km integer default null,
  p_protection_package text default 'standard'
)
returns public.bookings
language plpgsql
security definer
set search_path = ''
as $$
declare
  existing_booking public.bookings;
  updated_booking public.bookings;
  selected_vehicle public.vehicles;
  v_rental_days integer;
  previous_snapshot jsonb;
  new_total numeric(12, 2);
  new_subtotal numeric(12, 2);
  new_delivery_fee numeric(12, 2) := 10000;
  new_one_way_fee numeric(12, 2);
  new_protection_fee numeric(12, 2);
  new_mileage_fee numeric(12, 2);
  new_add_on_total numeric(12, 2);
  new_discount numeric(12, 2);
begin
  select * into existing_booking
  from public.bookings
  where id = p_booking_id and customer_id = (select auth.uid())
  for update;

  if existing_booking.id is null then
    raise exception 'Booking not found' using errcode = 'P0002';
  end if;
  if existing_booking.status not in ('pending', 'confirmed') then
    raise exception 'This booking can no longer be modified' using errcode = 'P0001';
  end if;
  if existing_booking.pickup_at <= now() + interval '4 hours' then
    raise exception 'Bookings can only be modified at least 4 hours before pickup' using errcode = 'P0001';
  end if;
  if p_dropoff_at <= p_pickup_at then
    raise exception 'Drop-off must be later than pickup' using errcode = '22007';
  end if;

  if exists (
    select 1
    from public.bookings booking
    where booking.vehicle_id = existing_booking.vehicle_id
      and booking.id <> existing_booking.id
      and booking.status in ('pending', 'confirmed', 'active')
      and tstzrange(booking.pickup_at, booking.dropoff_at, '[)')
        && tstzrange(p_pickup_at, p_dropoff_at, '[)')
  ) or exists (
    select 1
    from public.fleet_blocks block
    where block.vehicle_id = existing_booking.vehicle_id
      and tstzrange(block.starts_at, block.ends_at, '[)')
        && tstzrange(p_pickup_at, p_dropoff_at, '[)')
  ) then
    raise exception 'Vehicle is already booked or blocked for the selected dates' using errcode = '23P01';
  end if;

  select * into selected_vehicle from public.vehicles where id = existing_booking.vehicle_id;
  v_rental_days := greatest(1, ceil(extract(epoch from (p_dropoff_at - p_pickup_at)) / 86400.0)::integer);
  new_subtotal := selected_vehicle.price_per_day * v_rental_days;
  new_one_way_fee := case when lower(existing_booking.pickup_location) <> lower(coalesce(p_dropoff_location, existing_booking.dropoff_location)) then 25000 else 0 end;
  new_protection_fee := case coalesce(p_protection_package, existing_booking.protection_package)
    when 'plus' then v_rental_days * 15000
    when 'premium' then v_rental_days * 25000
    else 0
  end;
  new_mileage_fee := case
    when coalesce(p_mileage_package_km, 0) >= 2000 then 50000
    when coalesce(p_mileage_package_km, 0) >= 1000 then 25000
    else 0
  end;
  select coalesce(sum(
    case add_on.price_type
      when 'per_day' then add_on.price_amount * v_rental_days
      else add_on.price_amount
    end
  ), 0)
  into new_add_on_total
  from public.booking_add_ons add_on
  where add_on.code = any(coalesce(p_add_on_codes, '{}'::text[]))
    and add_on.applies_to = 'rental'
    and add_on.is_active;
  new_discount := case when upper(coalesce(p_coupon_code, '')) = 'KARIBU10000' then 10000 else 0 end
    + case when v_rental_days >= 90 then new_subtotal * 0.15 when v_rental_days >= 28 then new_subtotal * 0.10 else 0 end;
  new_total := greatest(0, new_subtotal + new_delivery_fee + new_one_way_fee + new_protection_fee + new_mileage_fee + new_add_on_total - new_discount);

  previous_snapshot := jsonb_build_object(
    'pickup_at', existing_booking.pickup_at,
    'dropoff_at', existing_booking.dropoff_at,
    'dropoff_location', existing_booking.dropoff_location,
    'total_price', existing_booking.total_price
  );

  update public.bookings
  set pickup_at = p_pickup_at,
      dropoff_at = p_dropoff_at,
      dropoff_location = coalesce(p_dropoff_location, dropoff_location),
      rental_days = v_rental_days,
      rental_product = case when v_rental_days >= 28 then 'long_term' else 'short_term' end,
      protection_package = coalesce(p_protection_package, protection_package),
      mileage_package_km = p_mileage_package_km,
      selected_addons = to_jsonb(coalesce(p_add_on_codes, '{}'::text[])),
      subtotal = new_subtotal,
      add_ons_total = new_add_on_total + new_protection_fee + new_mileage_fee,
      one_way_fee = new_one_way_fee,
      long_term_discount = case when v_rental_days >= 90 then new_subtotal * 0.15 when v_rental_days >= 28 then new_subtotal * 0.10 else 0 end,
      discount = new_discount,
      total_price = new_total
  where id = existing_booking.id
  returning * into updated_booking;

  insert into public.booking_amendments (booking_id, changed_by, previous_values, new_values, price_delta)
  values (
    updated_booking.id,
    (select auth.uid()),
    previous_snapshot,
    jsonb_build_object(
      'pickup_at', updated_booking.pickup_at,
      'dropoff_at', updated_booking.dropoff_at,
      'dropoff_location', updated_booking.dropoff_location,
      'total_price', updated_booking.total_price
    ),
    updated_booking.total_price - existing_booking.total_price
  );

  return updated_booking;
end;
$$;

create or replace function public.cancel_own_booking(p_booking_id uuid)
returns public.bookings
language plpgsql
security definer
set search_path = ''
as $$
declare
  existing_booking public.bookings;
  updated_booking public.bookings;
  fee numeric(12, 2);
begin
  select * into existing_booking from public.bookings
  where id = p_booking_id and customer_id = (select auth.uid()) for update;
  if existing_booking.id is null then
    raise exception 'Booking not found' using errcode = 'P0002';
  end if;
  if existing_booking.status not in ('pending', 'confirmed') then
    raise exception 'This booking can no longer be cancelled' using errcode = 'P0001';
  end if;

  fee := case
    when existing_booking.pickup_at <= now() + interval '24 hours' then round(existing_booking.total_price * 0.20, 2)
    when existing_booking.pickup_at <= now() + interval '48 hours' then round(existing_booking.total_price * 0.10, 2)
    else 0
  end;

  update public.bookings
  set status = 'cancelled', cancelled_at = now(), cancellation_fee = fee
  where id = p_booking_id returning * into updated_booking;

  if fee > 0 then
    insert into public.booking_line_items (booking_id, item_type, code, description, amount)
    values (updated_booking.id, 'cancellation', 'cancellation_fee', 'Cancellation fee', fee);
  end if;

  insert into public.booking_status_history (booking_id, from_status, to_status, changed_by)
  values (updated_booking.id, existing_booking.status, 'cancelled', (select auth.uid()));
  return updated_booking;
end;
$$;

create or replace function public.set_booking_status(
  p_booking_id uuid,
  p_status public.booking_status
)
returns public.bookings
language plpgsql
security definer
set search_path = ''
as $$
declare
  existing_booking public.bookings;
  updated_booking public.bookings;
  caller_role public.app_role;
  earned_points integer;
  new_status_points integer;
begin
  caller_role := public.current_app_role();
  select * into existing_booking from public.bookings where id = p_booking_id for update;
  if existing_booking.id is null then
    raise exception 'Booking not found' using errcode = 'P0002';
  end if;
  if caller_role <> 'admin' and not exists (
    select 1 from public.vehicles
    where id = existing_booking.vehicle_id and owner_id = (select auth.uid())
  ) then
    raise exception 'Not allowed to update this booking' using errcode = '42501';
  end if;

  update public.bookings
  set status = p_status,
      cancelled_at = case when p_status = 'cancelled' then now() else cancelled_at end
  where id = p_booking_id
  returning * into updated_booking;

  insert into public.booking_status_history (booking_id, from_status, to_status, changed_by)
  values (updated_booking.id, existing_booking.status, updated_booking.status, (select auth.uid()));

  if p_status = 'completed' and existing_booking.status <> 'completed' and updated_booking.customer_id is not null then
    earned_points := floor(updated_booking.total_price / 10000)::integer;
    insert into public.loyalty_accounts (customer_id, rental_points, status_points, lifetime_spend)
    values (updated_booking.customer_id, greatest(earned_points, 0), greatest(earned_points, 0), updated_booking.total_price)
    on conflict (customer_id) do update
    set rental_points = public.loyalty_accounts.rental_points + greatest(earned_points, 0),
        status_points = public.loyalty_accounts.status_points + greatest(earned_points, 0),
        lifetime_spend = public.loyalty_accounts.lifetime_spend + updated_booking.total_price,
        updated_at = now();

    insert into public.loyalty_transactions (customer_id, booking_id, points, transaction_type, description)
    values (updated_booking.customer_id, updated_booking.id, greatest(earned_points, 0), 'earned', 'Completed rental reward');

    select status_points into new_status_points
    from public.loyalty_accounts
    where customer_id = updated_booking.customer_id;

    update public.loyalty_accounts
    set tier = case
        when new_status_points >= 6000 then 'diamond'
        when new_status_points >= 4000 then 'platinum'
        when new_status_points >= 2000 then 'gold'
        else 'silver'
      end,
      tier_expires_on = (date_trunc('year', now()) + interval '2 years' - interval '1 day')::date
    where customer_id = updated_booking.customer_id;
  end if;

  return updated_booking;
end;
$$;

create or replace function public.create_business_account(
  p_company_name text,
  p_tax_id text,
  p_invoice_email text,
  p_billing_address text
)
returns public.business_accounts
language plpgsql
security definer
set search_path = ''
as $$
declare
  created_account public.business_accounts;
begin
  if (select auth.uid()) is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  insert into public.business_accounts (company_name, tax_id, invoice_email, billing_address, created_by)
  values (p_company_name, p_tax_id, p_invoice_email, p_billing_address, (select auth.uid()))
  returning * into created_account;

  insert into public.business_account_members (business_account_id, profile_id, member_role)
  values (created_account.id, (select auth.uid()), 'owner');

  return created_account;
end;
$$;

create or replace function public.review_business_account(
  p_business_account_id uuid,
  p_status text,
  p_discount_percent numeric default null
)
returns public.business_accounts
language plpgsql
security definer
set search_path = ''
as $$
declare
  result public.business_accounts;
begin
  if not public.is_admin() then
    raise exception 'Admin access required' using errcode = '42501';
  end if;
  if p_status not in ('approved', 'suspended') then
    raise exception 'Unsupported business account status' using errcode = '22023';
  end if;

  update public.business_accounts
  set status = p_status,
      discount_percent = coalesce(p_discount_percent, discount_percent),
      approved_by = case when p_status = 'approved' then (select auth.uid()) else approved_by end
  where id = p_business_account_id
  returning * into result;

  return result;
end;
$$;

create or replace function public.create_fleet_block(
  p_vehicle_id uuid,
  p_block_type text,
  p_starts_at timestamptz,
  p_ends_at timestamptz,
  p_reason text default null
)
returns public.fleet_blocks
language plpgsql
security definer
set search_path = ''
as $$
declare
  result public.fleet_blocks;
begin
  if p_ends_at <= p_starts_at then
    raise exception 'Block end must be later than start' using errcode = '22007';
  end if;
  if not public.is_admin() and not exists (
    select 1 from public.vehicles
    where id = p_vehicle_id and owner_id = (select auth.uid())
  ) then
    raise exception 'Not allowed to block this vehicle' using errcode = '42501';
  end if;

  insert into public.fleet_blocks (vehicle_id, block_type, starts_at, ends_at, reason, created_by)
  values (p_vehicle_id, p_block_type, p_starts_at, p_ends_at, p_reason, (select auth.uid()))
  returning * into result;

  return result;
exception
  when exclusion_violation then
    raise exception 'This vehicle already has a block during the selected time' using errcode = '23P01';
end;
$$;

create or replace function public.generate_booking_invoice(p_booking_id uuid)
returns public.invoices
language plpgsql
security definer
set search_path = ''
as $$
declare
  booking public.bookings;
  result public.invoices;
begin
  select * into booking
  from public.bookings
  where id = p_booking_id
    and (
      customer_id = (select auth.uid())
      or public.is_admin()
      or exists (
        select 1 from public.vehicles
        where vehicles.id = bookings.vehicle_id
          and vehicles.owner_id = (select auth.uid())
      )
      or (
        business_account_id is not null
        and public.is_business_member(business_account_id)
      )
    );

  if booking.id is null then
    raise exception 'Booking not found' using errcode = 'P0002';
  end if;

  insert into public.invoices (
    invoice_number, booking_id, business_account_id, customer_id,
    subtotal, total_amount, currency, due_at
  ) values (
    'RAR-' || to_char(now(), 'YYYYMMDD') || '-' || upper(left(replace(booking.id::text, '-', ''), 8)),
    booking.id, booking.business_account_id, booking.customer_id,
    booking.total_price, booking.total_price, booking.currency,
    case when booking.business_account_id is not null then now() + interval '30 days' else now() end
  )
  on conflict (invoice_number) do update
  set total_amount = excluded.total_amount
  returning * into result;

  return result;
end;
$$;

create or replace function public.create_subscription(
  p_vehicle_id uuid,
  p_preferred_model text,
  p_monthly_price numeric,
  p_mileage_package_km integer,
  p_protection_package text default 'standard',
  p_business_account_id uuid default null
)
returns public.subscriptions
language plpgsql
security definer
set search_path = ''
as $$
declare
  result public.subscriptions;
begin
  if (select auth.uid()) is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;
  if p_business_account_id is not null and not public.is_business_member(p_business_account_id) then
    raise exception 'Not allowed to use this business account' using errcode = '42501';
  end if;

  insert into public.subscriptions (
    customer_id, business_account_id, vehicle_id, preferred_model, monthly_price,
    mileage_package_km, protection_package, starts_at, next_billing_at
  ) values (
    (select auth.uid()), p_business_account_id, p_vehicle_id, p_preferred_model,
    p_monthly_price, p_mileage_package_km, p_protection_package, now(), now() + interval '30 days'
  )
  returning * into result;

  return result;
end;
$$;

create or replace function public.pause_subscription(
  p_subscription_id uuid,
  p_paused_until timestamptz
)
returns public.subscriptions
language plpgsql
security definer
set search_path = ''
as $$
declare
  result public.subscriptions;
begin
  update public.subscriptions
  set status = 'paused', paused_until = p_paused_until
  where id = p_subscription_id
    and customer_id = (select auth.uid())
    and p_paused_until <= now() + interval '3 months'
  returning * into result;

  if result.id is null then
    raise exception 'Subscription not found or pause period is too long' using errcode = 'P0002';
  end if;

  return result;
end;
$$;

create or replace function public.create_ride_booking(
  p_service_type text,
  p_pickup_at timestamptz,
  p_pickup_location text,
  p_destination_location text,
  p_hours integer,
  p_passenger_count smallint,
  p_luggage_count smallint,
  p_ride_class text,
  p_contact_email text,
  p_contact_phone text,
  p_business_account_id uuid default null
)
returns public.ride_bookings
language plpgsql
security definer
set search_path = ''
as $$
declare
  result public.ride_bookings;
  base_price numeric(12, 2);
  class_multiplier numeric(6, 2);
begin
  if (select auth.uid()) is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;
  if p_business_account_id is not null and not public.is_business_member(p_business_account_id) then
    raise exception 'Not allowed to use this business account' using errcode = '42501';
  end if;

  base_price := case p_service_type
    when 'hourly_chauffeur' then greatest(coalesce(p_hours, 1), 1) * 55000
    when 'airport_transfer' then 75000
    else 50000
  end;
  class_multiplier := case p_ride_class
    when 'first' then 2.2
    when 'business' then 1.6
    when 'xl' then 1.8
    when 'green' then 1.3
    else 1
  end;

  insert into public.ride_bookings (
    customer_id, business_account_id, service_type, pickup_at, pickup_location,
    destination_location, hours, passenger_count, luggage_count, ride_class,
    estimated_price, contact_email, contact_phone
  ) values (
    (select auth.uid()), p_business_account_id, p_service_type, p_pickup_at, p_pickup_location,
    p_destination_location, p_hours, coalesce(p_passenger_count, 1), coalesce(p_luggage_count, 0),
    coalesce(p_ride_class, 'standard'), round(base_price * class_multiplier, 2),
    p_contact_email, p_contact_phone
  )
  returning * into result;

  return result;
end;
$$;

alter table public.booking_add_ons enable row level security;
alter table public.business_accounts enable row level security;
alter table public.business_account_members enable row level security;
alter table public.loyalty_accounts enable row level security;
alter table public.loyalty_transactions enable row level security;
alter table public.booking_line_items enable row level security;
alter table public.booking_amendments enable row level security;
alter table public.fleet_blocks enable row level security;
alter table public.invoices enable row level security;
alter table public.subscriptions enable row level security;
alter table public.ride_bookings enable row level security;

revoke all on public.booking_add_ons, public.business_accounts, public.business_account_members,
  public.loyalty_accounts, public.loyalty_transactions, public.booking_line_items,
  public.booking_amendments, public.fleet_blocks, public.invoices, public.subscriptions,
  public.ride_bookings from anon, authenticated;

grant select on public.booking_add_ons to anon, authenticated;
grant select on public.business_accounts, public.business_account_members, public.loyalty_accounts,
  public.loyalty_transactions, public.booking_line_items, public.booking_amendments,
  public.fleet_blocks, public.invoices, public.subscriptions, public.ride_bookings to authenticated;
grant usage, select on all sequences in schema public to authenticated;

revoke execute on function public.ensure_loyalty_account(uuid), public.is_business_member(uuid),
  public.quote_booking(uuid, timestamptz, timestamptz, text, text, text, text, text[], uuid, integer, text),
  public.create_booking(uuid, timestamptz, timestamptz, text, text, text, text, text, text, text, text, text[], uuid, integer, text),
  public.modify_own_booking(uuid, timestamptz, timestamptz, text, text, text[], integer, text),
  public.create_business_account(text, text, text, text),
  public.review_business_account(uuid, text, numeric),
  public.create_fleet_block(uuid, text, timestamptz, timestamptz, text),
  public.generate_booking_invoice(uuid),
  public.create_subscription(uuid, text, numeric, integer, text, uuid),
  public.pause_subscription(uuid, timestamptz),
  public.create_ride_booking(text, timestamptz, text, text, integer, smallint, smallint, text, text, text, uuid)
from public;

grant execute on function public.quote_booking(uuid, timestamptz, timestamptz, text, text, text, text, text[], uuid, integer, text) to anon, authenticated;
grant execute on function public.ensure_loyalty_account(uuid), public.is_business_member(uuid),
  public.create_booking(uuid, timestamptz, timestamptz, text, text, text, text, text, text, text, text, text[], uuid, integer, text),
  public.modify_own_booking(uuid, timestamptz, timestamptz, text, text, text[], integer, text),
  public.create_business_account(text, text, text, text),
  public.review_business_account(uuid, text, numeric),
  public.create_fleet_block(uuid, text, timestamptz, timestamptz, text),
  public.generate_booking_invoice(uuid),
  public.create_subscription(uuid, text, numeric, integer, text, uuid),
  public.pause_subscription(uuid, timestamptz),
  public.create_ride_booking(text, timestamptz, text, text, integer, smallint, smallint, text, text, text, uuid)
to authenticated;

create policy "booking_add_ons_public_read" on public.booking_add_ons for select to anon, authenticated
using (is_active);

create policy "business_accounts_member_read" on public.business_accounts for select to authenticated
using (
  public.is_admin()
  or exists (
    select 1 from public.business_account_members member
    where member.business_account_id = business_accounts.id
      and member.profile_id = (select auth.uid())
  )
);

create policy "business_account_members_member_read" on public.business_account_members for select to authenticated
using (
  public.is_admin()
  or profile_id = (select auth.uid())
  or exists (
    select 1 from public.business_account_members self_member
    where self_member.business_account_id = business_account_members.business_account_id
      and self_member.profile_id = (select auth.uid())
      and self_member.member_role in ('owner', 'manager')
  )
);

create policy "loyalty_accounts_own_read" on public.loyalty_accounts for select to authenticated
using (customer_id = (select auth.uid()) or public.is_admin());

create policy "loyalty_transactions_own_read" on public.loyalty_transactions for select to authenticated
using (customer_id = (select auth.uid()) or public.is_admin());

create policy "booking_line_items_participant_read" on public.booking_line_items for select to authenticated
using (exists (
  select 1
  from public.bookings booking
  join public.vehicles vehicle on vehicle.id = booking.vehicle_id
  where booking.id = booking_line_items.booking_id
    and (
      booking.customer_id = (select auth.uid())
      or vehicle.owner_id = (select auth.uid())
      or public.is_admin()
      or (booking.business_account_id is not null and public.is_business_member(booking.business_account_id))
    )
));

create policy "booking_amendments_participant_read" on public.booking_amendments for select to authenticated
using (exists (
  select 1
  from public.bookings booking
  join public.vehicles vehicle on vehicle.id = booking.vehicle_id
  where booking.id = booking_amendments.booking_id
    and (
      booking.customer_id = (select auth.uid())
      or vehicle.owner_id = (select auth.uid())
      or public.is_admin()
    )
));

create policy "fleet_blocks_owner_or_admin_read" on public.fleet_blocks for select to authenticated
using (
  public.is_admin()
  or exists (
    select 1 from public.vehicles
    where vehicles.id = fleet_blocks.vehicle_id
      and vehicles.owner_id = (select auth.uid())
  )
);

create policy "invoices_participant_read" on public.invoices for select to authenticated
using (
  customer_id = (select auth.uid())
  or public.is_admin()
  or (business_account_id is not null and public.is_business_member(business_account_id))
);

create policy "subscriptions_participant_read" on public.subscriptions for select to authenticated
using (
  customer_id = (select auth.uid())
  or public.is_admin()
  or (business_account_id is not null and public.is_business_member(business_account_id))
);

create policy "ride_bookings_participant_read" on public.ride_bookings for select to authenticated
using (
  customer_id = (select auth.uid())
  or public.is_admin()
  or (business_account_id is not null and public.is_business_member(business_account_id))
);
